#!/usr/bin/env python
"""Markdown assembly for the Phase 1.6 extended evaluation report.

Split out of ``analyze_phase1_6_extended.py`` so the statistics and the prose
live apart: a change to a table's wording cannot then touch a bootstrap.

The section order is fixed by the task brief (section 18) and the vocabulary is
constrained by it: this report may not describe a single seed as reproducible,
may not call a rotation improvement an improvement in MD dynamics, may not call
dRMSD a thermodynamic or kinetic quantity, may not generalise an oracle failure
into a claim about forces, and may not report a metric the reconstruction cannot
support. Where a conclusion is not available from one bounded seed, the report
says so instead of choosing one.
"""

from __future__ import annotations


import numpy as np

IDENTITY = "identity_baseline"
LAGS = (1.0, 4.0)


def build_report(*, by_arm, scored, problems, manifest, plots_dir, helpers) -> list[str]:
    per_arm_table = helpers["per_arm_table"]
    comparison_table = helpers["comparison_table"]
    stratified_table = helpers["stratified_table"]
    contact_table = helpers["contact_table"]
    values_of = helpers["values_of"]
    paired_delta = helpers["paired_delta"]
    residue_weighted = helpers["residue_weighted"]
    pooled_torsion = helpers["pooled_torsion"]
    cell = helpers["cell"]
    arm_order = helpers["arm_order"]

    lines: list[str] = [
        "# Phase 1.6 extended metrics — Stage M, bounded seed 0",
        "",
        "Generated by `scripts/analyze_phase1_6_extended.py` from records written "
        "by `scripts/evaluate_phase1_6_extended.py`.",
        "",
        "**No model was trained for this report.** The seven Stage B checkpoints "
        "were reloaded, their sha256 verified unchanged before and after, and "
        "re-scored on the same validation manifest with a wider metric suite.",
        "",
    ]

    # -- 1. purpose ------------------------------------------------------
    lines += [
        "## 1. What this evaluation was for",
        "",
        "Stage B separated the arms on two numbers: Cα RMSD and residue-frame "
        "rotation. `P1_pair_physics_frozen` improved rotation against "
        "`P0_pair_geometry_control` while being *worse* on Cα RMSD. Two numbers "
        "cannot say what that means, so this pass asks what kind of structure "
        "each arm is getting right:",
        "",
        "* is the improvement in **internal** geometry (dRMSD by sequence "
        "separation) or only in placement?",
        "* does any arm predict a contact **event** — a contact that forms or "
        "breaks between *t* and *t+lag* — rather than reproducing the contacts "
        "that never changed?",
        "* does the reconstructed backbone stay physical?",
        "",
        "It is a measurement pass. It does not decide Stage C, and one bounded "
        "seed cannot.",
        "",
    ]

    # -- 2. hashes -------------------------------------------------------
    lines += ["## 2. Checkpoints and data", ""]
    if problems:
        lines += [
            "**The arms did not score the same samples. Every comparison below "
            "is invalid:**", "",
        ] + [f"* {p}" for p in problems] + [""]
    else:
        sizes = {a: len(r) for a, r in scored.items()}
        one = next(iter(sizes.values())) if sizes else 0
        lines += [
            f"Every arm scored the identical set of **{one} `pair_id`s** "
            f"({one // 2} per lag), over "
            f"{len({r['domain_id'] for r in next(iter(scored.values()))})} held-out "
            "domains. Duplicate ids are a hard error in both the evaluator and "
            "the loader.",
            "",
        ]
    git = manifest.get("git", {})
    environment = manifest.get("environment", {})
    lines += [
        "| item | value |",
        "|---|---|",
        f"| git commit | `{str(git.get('commit'))[:12]}` |",
        f"| working tree | {'dirty (preserved)' if git.get('dirty') else 'clean'} |",
        f"| source diff sha256 | `{str(git.get('source_diff_hash'))[:12]}` |",
        f"| config sha256 | `{str(manifest.get('config_sha256'))[:12]}` |",
        f"| Python / PyTorch / e3nn | {environment.get('python')} / "
        f"{environment.get('torch')} / {environment.get('e3nn')} |",
        f"| device | {environment.get('gpu', environment.get('device'))} |",
        f"| dtype | model {environment.get('model_dtype')}; metrics "
        f"{environment.get('metric_dtype')} |",
        f"| retrained | {manifest.get('retrained')} |",
        f"| checkpoints verified unchanged | "
        f"{manifest.get('checkpoints_verified_unchanged')} |",
        "",
    ]
    arms_meta = manifest.get("arms", [])
    if arms_meta:
        lines += [
            "| arm | checkpoint sha256 | step | manifest | Phase 1 ckpt | config |",
            "|---|---|---|---|---|---|",
        ]
        for entry in arms_meta:
            lines.append(
                f"| `{entry['canonical_arm']}` | "
                f"`{str(entry['checkpoint_sha256'])[:12]}` | {entry.get('step')} | "
                f"`{str(entry.get('manifest_hash'))[:12]}` | "
                f"`{str(entry.get('phase1_sha256'))[:12]}` | "
                f"`{str(entry.get('config_hash'))[:12]}` |"
            )
        lines.append("")

    # -- 3. metric definitions -------------------------------------------
    lines += [
        "## 3. Metric definitions",
        "",
        "| metric | definition | unit |",
        "|---|---|---|",
        "| `ca_rmsd` | RMS ‖pred Cα − target Cα‖ over valid residues, in the "
        "canonical frame (§4) | Å |",
        "| `ca_rmsd_superposed` | as above after an **extra** per-sample Kabsch of "
        "the prediction onto the target | Å |",
        "| `translation_rmse` | RMS ‖Δ̂_local − Δ_local‖. The residue origin **is** "
        "the Cα, so this is algebraically `ca_rmsd`; it is not an independent "
        "metric and is not read as one | Å |",
        "| `rotation_geodesic_*_deg` | angle of `R̂ᵀR` per residue, via "
        "`atan2`, then mean / median over the sample | ° |",
        "| `drmsd_*` | RMS of (‖x̂ᵢ−x̂ⱼ‖ − ‖xᵢ−xⱼ‖) over a pair subset. "
        "Alignment-free by construction | Å |",
        "| `drmsd_local` / `medium` / `long_range` | `\\|i−j\\|` in 1–2 / 3–5 / ≥6, "
        "measured on source residue numbering within a chain | Å |",
        "| `drmsd_current_spatial_edges` | the probe's own Cα-kNN edge set, built "
        "on the **current** frame only | Å |",
        "| `contact_*` | Cα–Cα `d < 8.0 Å`, `\\|i−j\\| ≥ 6`, on the future structure | — |",
        "| `formed_contact_*` | restricted to pairs **not** in contact at *t*; a "
        "true positive is a correctly predicted new contact | — |",
        "| `broken_contact_*` | restricted to pairs **in** contact at *t* | — |",
        "| `phi/psi/omega_mae_deg` | mean circular error `\\|atan2(sin Δ, cos Δ)\\|` on "
        "the reconstructed N/Cα/C backbone | ° |",
        "| `bond_length_rmse` | C–N(next) peptide bond only — see §4 | Å |",
        "| `bond_angle_mae_deg` | Cα–C–N(next) and C–N(next)–Cα(next) only | ° |",
        "| `ca_neighbor_distance_mae` | `\\| ‖x̂ᵢ₊₁−x̂ᵢ‖ − ‖xᵢ₊₁−xᵢ‖ \\|` over bonded "
        "neighbours | Å |",
        "| `clash_rate` | fraction of Cα pairs with `\\|i−j\\| ≥ 2` closer than 3.6 Å. "
        "**Cα-only**, not an all-atom clash rate | — |",
        "",
    ]
    not_applicable = manifest.get("not_applicable", {})
    if not_applicable:
        lines += [
            "### Metrics this reconstruction cannot support",
            "",
            "Reported as `null` with the reason below, never as 0.",
            "",
            "| metric | why not |",
            "|---|---|",
        ]
        for key, reason in sorted(not_applicable.items()):
            lines.append(f"| `{key}` | {reason} |")
        lines.append("")

    # -- 4. alignment and masking ----------------------------------------
    lines += [
        "## 4. Alignment and masking",
        "",
        "`build_transition_target` fits **one** proper rotation (`det = +1`, no "
        "reflection, SVD in float64) taking the future Cα onto the current Cα, "
        "weighted by the residues valid in both structures, and moves the whole "
        "future structure by it. The prediction is built from the current frames, "
        "so prediction and target already share that canonical frame and every "
        "metric here is invariant to a rigid motion of the whole pair — asserted "
        "by test, not assumed.",
        "",
        "`ca_rmsd` and `rotation_geodesic_mean_deg` therefore do **no second "
        "superposition**, which is what makes them the Stage B definitions. The "
        "`*_superposed` variants do one, and apply the *same* rotation `Q` to the "
        "frames (`R̂ → QR̂`) as to the coordinates, so the two are a consistent "
        "pair — the existing `ca_rmsd_aligned` + `rotation_geodesic_deg` was not.",
        "",
        "A residue is excluded wherever the current frame, the future frame or the "
        "batch mask excludes it; a torsion is excluded across a chain break or a "
        "residue-numbering gap; a pair is excluded if either endpoint is. Every "
        "record carries the counts it actually used (`n_valid_residues`, "
        "`n_valid_pairs`, `n_valid_torsions`, `n_current_spatial_edges`).",
        "",
        "**The future is read only to score.** No function in the metric path takes "
        "a model, and no conditioner accepts a `TransitionTarget`.",
        "",
    ]

    # -- 5. reproduction --------------------------------------------------
    lines += ["## 5. Reproduction of the Stage B numbers", ""]
    lines += _reproduction_section(
        scored, values_of, residue_weighted, cell, arm_order
    )

    # -- 6-11. results ----------------------------------------------------
    for lag in LAGS:
        lines += [f"## 6.{int(lag)} All arms at {lag:g} ns", ""]
        for metric, label in (
            ("ca_rmsd", "Cα RMSD (co-primary)"),
            ("drmsd_long_range", "long-range dRMSD, sequence separation ≥ 6 (co-primary)"),
            ("rotation_geodesic_mean_deg", "rotation geodesic error"),
            ("drmsd_all", "dRMSD, all pairs"),
            ("drmsd_local", "dRMSD, sequence separation 1–2"),
            ("drmsd_medium", "dRMSD, sequence separation 3–5"),
            ("drmsd_current_spatial_edges", "dRMSD on the current spatial graph"),
            ("contact_f1", "static future contact F1 (sample macro)"),
            ("backbone_torsion_mae_deg", "backbone torsion MAE (φ, ψ, ω pooled)"),
        ):
            lines += [f"### {label}", ""]
            lines += per_arm_table(by_arm, metric, lag)
            lines.append("")

    lines += ["## 7–11. Paired comparisons", "",
              "Positive Δ always means **the candidate is better**, for every "
              "metric, higher-is-better ones included. Intervals are 95% cluster "
              f"bootstraps over domains, {manifest.get('bootstrap_iterations', 10000)} "
              "resamples unless stated.", ""]
    for lag in LAGS:
        for metric, label in (
            ("ca_rmsd", "Cα RMSD"),
            ("drmsd_long_range", "long-range dRMSD"),
            ("rotation_geodesic_mean_deg", "rotation geodesic error"),
            ("contact_f1", "static contact F1"),
            ("formed_contact_f1", "formed-contact F1"),
            ("broken_contact_f1", "broken-contact F1"),
            ("backbone_torsion_mae_deg", "backbone torsion MAE"),
        ):
            lines += [f"### {label} @ {lag:g} ns", ""]
            lines += comparison_table(scored, metric, lag)
            lines.append("")

    # -- 12. contacts ------------------------------------------------------
    lines += [
        "## 12. Contact formation and breakage",
        "",
        "Macro and micro are printed in separate columns and are never blended: "
        "macro is the mean over samples that had an event, micro is recomputed "
        "from pooled TP/FP/FN. A sample with no event of that kind contributes to "
        "neither and is counted in its own column.",
        "",
    ]
    for lag in LAGS:
        for prefix, label in (
            ("contact", "static future contacts"),
            ("formed_contact", "contacts that **form** between t and t+lag"),
            ("broken_contact", "contacts that **break** between t and t+lag"),
        ):
            lines += [f"### {label} @ {lag:g} ns", ""]
            lines += contact_table(by_arm, prefix, lag)
            lines.append("")
    lines += [
        "The identity baseline reproduces the current contact map exactly, so it "
        "forms nothing and breaks nothing. Its event **precision is undefined** — "
        "it made no predictions — while its event **F1 is 0.0**, because it missed "
        "every event that happened. Those are different statements and are printed "
        "as different columns.",
        "",
    ]

    # -- 13. torsions ------------------------------------------------------
    lines += [
        "## 13. Backbone torsions",
        "",
        "Three aggregations, kept apart because they weight differently: "
        "residue-pooled lets long proteins dominate, sample-macro counts every "
        "pair once, domain-macro counts every protein once.",
        "",
    ]
    for lag in LAGS:
        lines += [
            f"### {lag:g} ns",
            "",
            "| arm | residue-pooled | sample-macro | domain-macro | residues |",
            "|---|---|---|---|---|",
        ]
        for arm in arm_order(by_arm) + ([IDENTITY] if IDENTITY in by_arm else []):
            summary = pooled_torsion(by_arm[arm], lag)
            lines.append(
                f"| `{arm}` | {cell(summary['residue_pooled'])} | "
                f"{cell(summary['sample_macro'])} | {cell(summary['domain_macro'])} | "
                f"{summary['residues']} |"
            )
        lines.append("")
        for metric, label in (("phi_mae_deg", "φ"), ("psi_mae_deg", "ψ"),
                              ("omega_mae_deg", "ω")):
            lines += [f"#### {label} MAE @ {lag:g} ns", ""]
            lines += per_arm_table(by_arm, metric, lag)
            lines.append("")

    # -- 14. validity ------------------------------------------------------
    lines += [
        "## 14. Physical validity",
        "",
        "Only the inter-residue quantities are measurements. `reconstruct_backbone` "
        "carries each residue's **current** internal geometry onto the predicted "
        "frame and does the same for the target, so N–Cα, Cα–C, the N–Cα–C angle "
        "and Cβ chirality are identical on both sides by construction. They are "
        "reported as `null` in §3, not as 0.",
        "",
    ]
    lines += _validity_headline(by_arm, values_of, arm_order)
    for lag in LAGS:
        for metric, label in (
            ("bond_length_rmse", "C–N(next) peptide bond RMSE (Å)"),
            ("bond_angle_mae_deg", "backbone angle MAE across the peptide bond (°)"),
            ("ca_neighbor_distance_mae", "consecutive Cα distance MAE (Å)"),
            ("clash_rate", "Cα-only clash rate (d < 3.6 Å, sequence separation ≥ 2)"),
        ):
            lines += [f"### {label} @ {lag:g} ns", ""]
            lines += per_arm_table(by_arm, metric, lag, digits=6)
            lines.append("")

    # -- 15. stratification ------------------------------------------------
    lines += ["## 15. By lag, temperature and length", ""]
    for lag in LAGS:
        for metric in ("ca_rmsd", "drmsd_long_range", "contact_f1"):
            lines += [f"### {metric} by temperature @ {lag:g} ns", ""]
            lines += stratified_table(by_arm, metric, lag, "temperature")
            lines.append("")
        lines += [f"### ca_rmsd by protein length @ {lag:g} ns", ""]
        lines += stratified_table(by_arm, "ca_rmsd", lag, "length_bin")
        lines.append("")
    lines += [
        "DSSP secondary-structure and RMSF-based flexibility stratification are "
        "`not_applicable` for this run; the reasons are in §3 and in "
        "`reproducibility_manifest.json`. They were not approximated.",
        "",
    ]

    # -- appendix: contact threshold sensitivity ---------------------------
    lines += [
        "## Appendix A. Contact-threshold sensitivity",
        "",
        "Reported to show the primary conclusion is not an artefact of 8.0 Å. "
        "**Not used to choose an arm**, and the primary threshold was fixed before "
        "the run.",
        "",
    ]
    for lag in LAGS:
        for metric, label in (
            ("contact_f1_cut6", "contact F1 at 6 Å"),
            ("contact_f1_cut10", "contact F1 at 10 Å"),
            ("contact_f1_legacy_sep3", "Stage B contact F1 (8 Å, sequence separation ≥ 3)"),
        ):
            lines += [f"### {label} @ {lag:g} ns", ""]
            lines += per_arm_table(by_arm, metric, lag)
            lines.append("")

    # -- 16-18. limits, decision, recommendation ---------------------------
    lines += _conclusions_section(scored, values_of, paired_delta)

    # -- 19. reproduce -----------------------------------------------------
    lines += [
        "## 19. Reproducing this report",
        "",
        "```bash",
        "# Stage M0 — metric unit tests",
        "python -m pytest tests/test_extended_metrics.py "
        "tests/test_extended_analysis.py -q",
        "",
        "# Stage M1 — re-score the frozen checkpoints (no training)",
        "python scripts/evaluate_phase1_6_extended.py \\",
        "    --run runs/phase1_6_bounded_seed0 \\",
        "    --config configs/phase1_6_bounded.yaml \\",
        "    --out runs/phase1_6_extended_metrics_seed0 \\",
        "    --device cuda:4",
        "",
        "# Stage M2 — aggregate and report",
        "python scripts/analyze_phase1_6_extended.py \\",
        "    --records runs/phase1_6_extended_metrics_seed0/records.jsonl \\",
        "    --out docs/phase1_6_results_extended.md \\",
        "    --plots docs/figures",
        "```",
        "",
    ]

    if plots_dir:
        written = helpers["write_plots"](by_arm, plots_dir)
        lines += [
            "## Figures",
            "",
            "Error bars are 95% domain **cluster** bootstraps, not frame-level "
            "intervals.",
            "",
        ] + [f"* `{p}`" for p in written] + [""]

    return lines


def _validity_headline(by_arm, values_of, arm_order):
    """State the identity-relative validity result, computed rather than written.

    The per-metric tables below carry it, but spread over eight tables and two
    lags it is easy to read past -- and it is the one place where the ranking
    inverts: the identity baseline is a real MD frame, so its inter-residue
    geometry is a real protein's, while every trained arm moves residue frames
    independently and pays for its placement gain in chain geometry. A summary
    that a reader has to assemble themselves is a summary that will not be
    assembled.

    Every number here is a ratio of two measured means. Nothing is asserted that
    the tables below do not also show.
    """
    if IDENTITY not in by_arm:
        return []
    metrics = (
        ("bond_length_rmse", "C–N(next) bond RMSE"),
        ("bond_angle_mae_deg", "backbone angle MAE"),
        ("ca_neighbor_distance_mae", "consecutive Cα distance MAE"),
        ("clash_rate", "Cα clash rate"),
        ("backbone_torsion_mae_deg", "backbone torsion MAE"),
    )
    lines = [
        "### Every trained arm is less physical than predicting no motion",
        "",
        "| metric | lag | identity baseline | best arm | ratio (arm / identity) |",
        "|---|---|---|---|---|",
    ]
    inverted = 0
    total = 0
    for metric, label in metrics:
        for lag in LAGS:
            base_values = values_of(by_arm[IDENTITY], metric, lag=lag)
            if not base_values:
                continue
            base = float(np.mean(list(base_values.values())))
            candidates = {}
            for arm in arm_order(by_arm):
                values = values_of(by_arm[arm], metric, lag=lag)
                if values:
                    candidates[arm] = float(np.mean(list(values.values())))
            if not candidates:
                continue
            best_arm = min(candidates, key=candidates.get)
            best = candidates[best_arm]
            total += 1
            if best > base:
                inverted += 1
            ratio = best / base if base else float("nan")
            lines.append(
                f"| {label} | {lag:g} ns | {base:.5g} | {best:.5g} "
                f"(`{best_arm.split('_')[0]}`) | **{ratio:.1f}×** |"
            )
    lines += [
        "",
        f"The best arm is worse than the identity baseline in **{inverted} of "
        f"{total}** of these cells. The direction is not a surprise once stated: "
        "\"nothing moves\" returns a real mdCATH frame, whose peptide bonds, "
        "backbone angles and packing are a real protein's, so it can only be beaten "
        "on chain geometry by a model that predicts chain geometry. These arms "
        "predict a **rigid update per residue frame** and each frame moves "
        "independently, so the bonds *between* residues absorb the error. Whatever "
        "the arms buy in Cα placement and pair distances, they pay for here.",
        "",
        "Three things this does **not** say. It is not a defect in the metric: the "
        "same reconstruction is applied to prediction and target, so both carry the "
        "same intra-residue approximation (§3). It is not a training failure: the "
        "loss these checkpoints minimised has `clash: 0.0` and no bond term, so "
        "chain geometry was never optimised and this is what that costs. And it is "
        "not a reason to prefer the identity baseline, which is worse on every "
        "endpoint and predicts no transition event at all.",
        "",
    ]
    return lines


def _reproduction_section(scored, values_of, residue_weighted, cell, arm_order):
    """The Stage B check: same definition, same number, both weightings shown."""
    lines = [
        "Two aggregations exist in this repository and the Stage B report never "
        "said which it quoted. Both are printed here. The **sample-equal mean** is "
        "the primary (every evaluation pair counts once, brief §12.1); the "
        "**residue-weighted mean** is what `results.csv` and the runner console "
        "print, where a 250-residue domain counts five times a 50-residue one.",
        "",
        "| arm | lag | ca_rmsd, sample-equal | ca_rmsd, residue-weighted | "
        "rotation, sample-equal | rotation, residue-weighted |",
        "|---|---|---|---|---|---|",
    ]
    for arm in arm_order(scored):
        for lag in LAGS:
            records = scored[arm]
            ca = values_of(records, "ca_rmsd", lag=lag)
            rotation = values_of(records, "rotation_geodesic_mean_deg", lag=lag)
            lines.append(
                f"| `{arm}` | {lag:g} ns | "
                f"{cell(float(np.mean(list(ca.values()))) if ca else float('nan'))} | "
                f"{cell(residue_weighted(records, 'ca_rmsd', lag))} | "
                f"{cell(float(np.mean(list(rotation.values()))) if rotation else float('nan'), 3)} | "
                f"{cell(residue_weighted(records, 'rotation_geodesic_mean_deg', lag), 3)} |"
            )
    lines += [
        "",
        "Compare against `docs/phase1_6_results_bounded.md` (sample-equal column) "
        "and `runs/phase1_6_bounded_seed0/results.csv` (`aggregation=micro` rows, "
        "residue-weighted column). Agreement to the printed precision means the "
        "extended suite inherited the definitions rather than re-inventing them.",
        "",
    ]
    return lines


def _conclusions_section(scored, values_of, paired_delta):
    """§16–18: limits, the decision matrix, and whether more seeds are warranted.

    The interpretation rules come from the brief and are applied mechanically to
    the measured deltas, so the text cannot drift from the table above it.
    """
    lines = [
        "## 16. What one bounded seed can and cannot support",
        "",
        "* **One training seed.** Every interval here is a domain cluster "
        "bootstrap over the *evaluation* set. It quantifies how much the result "
        "depends on which 30 proteins were held out. It says nothing about how "
        "much it depends on the training seed, and no across-seed standard "
        "deviation is quoted because none exists.",
        "* A separation at 95% here is **not** a reproducible superiority. Phase "
        "1.5 measured arms that differed by ~0.2% and needed three seeds to say "
        "anything about them.",
        "* The budget is Stage B's: 6,000 steps, three replicas, 120 train "
        "domains. These are screening numbers.",
        "* dRMSD, contacts and torsions are **structural** measures of a single "
        "deterministic endpoint prediction. None of them is a thermodynamic or "
        "kinetic quantity, and none is evidence about ensemble fidelity.",
        "* A change in residue-frame rotation error is a change in predicted "
        "frame orientation. It is not, on its own, an improvement in molecular "
        "dynamics.",
        "* `P3`, `P4` and `P5` were not run. No number is estimated for them.",
        "",
    ]

    findings: dict[str, dict] = {}
    for lag in LAGS:
        for control, candidate, label in (
            ("S0_structure_history", "P0_pair_geometry_control", "P0−S0"),
            ("P0_pair_geometry_control", "P1_pair_physics_frozen", "P1−P0"),
            ("P1_pair_physics_frozen", "P2_pair_physics_moments", "P2−P1"),
            ("S0_structure_history", "S2_node_physics_152d", "S2−S0"),
            ("S0_structure_history", "O_current_gt_force_oracle", "O−S0"),
        ):
            if control not in scored or candidate not in scored:
                continue
            for metric in ("ca_rmsd", "drmsd_long_range",
                           "rotation_geodesic_mean_deg", "contact_f1",
                           "formed_contact_f1", "backbone_torsion_mae_deg",
                           "clash_rate", "bond_length_rmse"):
                findings[f"{label}|{metric}|{lag}"] = paired_delta(
                    values_of(scored[control], metric, lag=lag),
                    values_of(scored[candidate], metric, lag=lag),
                    metric,
                )

    def sign(label: str, metric: str) -> str:
        """Consistent across both lags, or 'mixed' / 'not separated'."""
        results = [findings.get(f"{label}|{metric}|{lag}") for lag in LAGS]
        results = [r for r in results if r and r["n"]]
        if not results:
            return "not run"
        separated = [r for r in results if r["significant"]]
        if not separated:
            return "not separated"
        directions = {r["delta"] > 0 for r in separated}
        if len(directions) > 1:
            return "mixed across lags"
        if len(separated) < len(results):
            return ("better at one lag only" if next(iter(directions))
                    else "worse at one lag only")
        return "better at both lags" if next(iter(directions)) else "worse at both lags"

    lines += [
        "## 17. Decision matrix",
        "",
        "Read mechanically off the paired tables. A cell is `better/worse at both "
        "lags` only when the 95% domain-cluster interval excludes zero at 1 ns "
        "**and** 4 ns in the same direction.",
        "",
        "| comparison | Cα RMSD | long-range dRMSD | rotation | contact F1 | "
        "formed-contact F1 | torsion MAE | clash rate | peptide bond |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for label in ("P0−S0", "P1−P0", "P2−P1", "S2−S0", "O−S0"):
        cells = [
            sign(label, m) for m in (
                "ca_rmsd", "drmsd_long_range", "rotation_geodesic_mean_deg",
                "contact_f1", "formed_contact_f1", "backbone_torsion_mae_deg",
                "clash_rate", "bond_length_rmse",
            )
        ]
        lines.append(f"| **{label}** | " + " | ".join(cells) + " |")
    lines.append("")

    # Mechanical application of the brief's interpretation rules.
    lines += ["### What the brief's rules say about these cells", ""]
    p1_rmsd = sign("P1−P0", "ca_rmsd")
    p1_drmsd = sign("P1−P0", "drmsd_long_range")
    p1_rotation = sign("P1−P0", "rotation_geodesic_mean_deg")
    p1_contact = sign("P1−P0", "contact_f1")
    p1_formed = sign("P1−P0", "formed_contact_f1")
    p1_torsion = sign("P1−P0", "backbone_torsion_mae_deg")
    p0_rmsd = sign("P0−S0", "ca_rmsd")
    p0_drmsd = sign("P0−S0", "drmsd_long_range")
    p2 = sign("P2−P1", "ca_rmsd")
    oracle = sign("O−S0", "ca_rmsd")

    if p0_rmsd == "not run":
        lines.append("* **P0 vs S0** — not run; nothing is concluded from it.")
    else:
        lines.append(
            f"* **P0 vs S0** — Cα RMSD *{p0_rmsd}*, long-range dRMSD *{p0_drmsd}*. "
            + (
                "The direction reproduces on both co-primaries, which supports the "
                "pair-geometry architecture itself."
                if p0_rmsd.startswith("better at both")
                and p0_drmsd.startswith("better at both")
                else "The two co-primaries do not both reproduce, so the "
                     "pair-geometry architecture is supported only as far as the "
                     "cells above state."
            )
        )
    only_rotation = (
        p1_rotation.startswith("better")
        and not p1_drmsd.startswith("better")
        and not p1_contact.startswith("better")
        and not p1_torsion.startswith("better")
    )
    lines.append(
        f"* **P1 vs P0** — rotation *{p1_rotation}*, Cα RMSD *{p1_rmsd}*, "
        f"long-range dRMSD *{p1_drmsd}*, contact F1 *{p1_contact}*, "
        f"formed-contact F1 *{p1_formed}*, torsion *{p1_torsion}*."
    )
    if p1_rmsd == "not run":
        lines.append(
            "  This comparison was not run, so nothing is concluded from it."
        )
    elif only_rotation:
        lines.append(
            "  Pair physics moves **frame orientation and nothing else**. Under "
            "the brief's rule this is not read as an improvement in transition "
            "performance and does not count as passing a Stage C gate: an "
            "orientation-only gain with no pair, contact or torsion gain is "
            "consistent with a better local-frame prior, not with better dynamics."
        )
    elif p1_drmsd.startswith("worse") or p1_rmsd.startswith("worse"):
        lines.append(
            "  Pair physics degrades at least one co-primary. Under the brief's "
            "rule the case for keeping it as a 1–4 ns transition conditioner is "
            "weak, and a `P3`/`P4`/`P5` full run is **not** recommended on this "
            "evidence."
        )
    else:
        lines.append(
            "  The cells above are the finding; they do not fall into one of the "
            "brief's clean cases and are not forced into one here."
        )
    # "not run" is its own branch everywhere below, and it comes first. A
    # comparison that did not happen must not reach a sentence that reads as a
    # finding about it -- which is exactly what an `if not better` fallback would
    # do, since "not run" is also "not better".
    if p2 == "not run":
        lines.append("* **P2 vs P1** — not run; nothing is concluded from it.")
    else:
        lines.append(
            f"* **P2 vs P1** — Cα RMSD *{p2}*. "
            + ("The explicit (F, τ, S) moment branch is not shown to add anything "
               "and is de-prioritised; its extra complexity is not carried into "
               "Phase 2 automatically."
               if not p2.startswith("better at both")
               else "The moment branch adds something on this seed; one seed is "
                    "not enough to adopt it.")
        )
    if oracle == "not run":
        lines.append("* **Oracle vs S0** — not run; nothing is concluded from it.")
    else:
        lines.append(
            f"* **Oracle vs S0** — Cα RMSD *{oracle}*. "
            + ("A conditioner reading ground-truth instantaneous forces does not "
               "beat the structure-only baseline **within this force encoding and "
               "this probe** at 1–4 ns. That is a statement about this setup, not "
               "about forces in general, and it is not an information-theoretic "
               "claim."
               if not oracle.startswith("better")
               else "The oracle separates from the baseline; the recoverability "
                    "ratio is then interpretable and is quoted in the tables "
                    "above.")
        )
    lines.append("")

    lines += [
        "## 18. Should more seeds be run?",
        "",
        "This is a recommendation. **No training was started and none will be "
        "without an explicit request.**",
        "",
    ]
    measured = {p0_rmsd, p0_drmsd, p1_rmsd, p1_drmsd, p2, oracle} != {"not run"}
    worth_it = p0_rmsd.startswith("better at both") or p0_drmsd.startswith("better at both")
    if not measured:
        lines += [
            "* Not enough of the comparison set was scored to recommend anything. "
            "No arm is ruled in or out here, because the comparisons that would "
            "do so were not run.",
        ]
    elif worth_it and not (p1_drmsd.startswith("better")
                           or p1_contact.startswith("better")):
        lines += [
            "* Seeds 1 and 2 of **Stage C are worth running for `P0` against "
            "`S0`** — that is the effect with a consistent direction on a "
            "co-primary at both lags, and three seeds is the smallest number that "
            "can say whether it survives re-initialisation.",
            "* Extending the same run to `P1` and `P2` costs little once the "
            "harness is up and is the cheapest way to test whether the "
            "orientation-only signal is a seed artefact.",
        ]
        # The reason to defer P3/P4/P5 is a *measured* absence of pair-physics
        # gain. If P1 was never scored there is no such measurement, and the
        # deferral has to be stated without one.
        lines.append(
            "* `P3`/`P4`/`P5` are **not** recommended: they elaborate the pair-"
            "physics branch, and the pair-physics branch has not been shown to "
            "improve any structural endpoint beyond orientation."
            if p1_drmsd != "not run"
            else "* `P3`/`P4`/`P5` stay gated. They elaborate the pair-physics "
                 "branch, and `P1` was not scored here, so there is no evidence "
                 "either way about it in this run."
        )
    elif worth_it:
        lines += [
            "* Stage C seeds 1 and 2 are worth running: more than one metric "
            "family moves in the same direction on this seed.",
            "* `P3`/`P4`/`P5` remain gated on that result.",
        ]
    else:
        lines += [
            "* No arm shows a consistent direction on a co-primary at both lags. "
            "Additional seeds of the same configuration would most likely resolve "
            "differences too small to matter.",
            "* The productive next step is a change of mechanism, not a change of "
            "seed.",
        ]
    lines.append("")
    return lines
